/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package conexion_mysql;

import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Asus
 */
public class Buscar extends javax.swing.JFrame {

    public final void initUI() {
    
        setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        
         this.addWindowListener(new WindowAdapter(){
        
                
            @Override
            public void windowClosing(WindowEvent we){
            
                dispose();
                
        }
        
        });
    
    }
    
    
    


    // Metodo constructor
    public Buscar() {
        initComponents();
        initUI();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDatos = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "idDocumento", "nombreUsuario", "apellidoUsuario", "usuario", "contrasena", "fecha" }));

        jLabel1.setText("Buscar por:");

        jButton1.setText("Buscar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        tblDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "IdDocumento", "nombreUsuario", "apellidoUsuario", "usuario", "contrasena", "fecha"
            }
        ));
        tblDatos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDatosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblDatos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 859, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(6, 6, 6)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jButton1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(159, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    Conexion conex = new Conexion();
    Connection conn = conex.conexion_mysql();
    
    DefaultTableModel ModeloTabla;
   
    
    // Metodo
    public void Buscar(String valor, String filtro, JTable tablaUsuarios){
    
        String [] columnas = {"ID", "Nombre", "Apellido", "usuario", "contraseña", "fecha"};
        String [] registro = new String[6];
        ModeloTabla  = new DefaultTableModel(null,columnas);      
        String SSQL;
       
        
        if(filtro.equals("apellidoUsuario")){
    
                SSQL= "SELECT idDocumento, nombreUsuario, apellidoUsuario, usuario, contrasena, fecha "
                 + "FROM usuarios WHERE apellidoUsuario LIKE '%"+valor+"%'";
        
        }else if(filtro.equals("nombreUsuario")){
    
                SSQL= "SELECT idDocumento, nombreUsuario, apellidoUsuario, usuario, contrasena, fecha "
                 + "FROM usuarios WHERE nombreUsuario LIKE '%"+valor+"%'";
    
        }else if(filtro.equals("usuario")){
    
                SSQL= "SELECT idDocumento, nombreUsuario, apellidoUsuario, usuario, contrasena, fecha "
                 + "FROM usuarios WHERE usuario LIKE '%"+valor+"%'";
    
        }else if(filtro.equals("contrasena")){
    
                SSQL= "SELECT idDocumento, nombreUsuario, apellidoUsuario, usuario, contrasena, fecha "
                 + "FROM usuarios WHERE contrasena LIKE '%"+valor+"%'";
    
        } else if(filtro.equals("idDocumento")){
    
                SSQL= "SELECT idDocumento, nombreUsuario, apellidoUsuario, usuario, contrasena, fecha "
                 + "FROM usuarios WHERE idDocumento LIKE '%"+valor+"%'";
                
                System.out.println(SSQL);
    
        }else if (filtro.equals("fecha")){
    
                SSQL= "SELECT idDocumento, nombreUsuario, apellidoUsuario, usuario, contrasena, fecha "
                 + "FROM usuarios WHERE fecha LIKE '%"+valor+"%'";
                
                System.out.println(SSQL);
                
        } else{
        
                SSQL= "SELECT * FROM usuarios;";
        
        
        }// Fin if
        
        //
        try (Statement st = conn.createStatement()) {
                
                // ejecuta la consulta y obtiene el resultado
                ResultSet rs = st.executeQuery(SSQL);
                
                // recorre la respuesta
                while (rs.next()) {
                 
                    registro[0] = rs.getString("idDocumento");
                    registro[1] = rs.getString("nombreUsuario");
                    registro[2] = rs.getString("apellidoUsuario");
                    registro[3] = rs.getString("usuario");
                    registro[4] = rs.getString("contrasena");
                    registro[5] = rs.getString("fecha");
                 
                    
                    ModeloTabla.addRow(registro);
                    
                }//fin while
                
                // llena la tabla de la vista
                tablaUsuarios.setModel(ModeloTabla);
                
            } catch (SQLException ex) {
                
                //en caso de error, imprime el tipo de error
                System.err.println(ex.getMessage());
            
            }//fin trycatch
    
        
    }// Fin del metodo Buscar
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        Buscar(jTextField1.getText(), jComboBox1.getSelectedItem().toString(), tblDatos);

        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void tblDatosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDatosMouseClicked
        // TODO add your handling code here:
        JTable source = (JTable)evt.getSource();
            int row = source.rowAtPoint(evt.getPoint());
            int column = source.columnAtPoint(evt.getPoint());
            
            String [] filaSeleccionada = new String[6]; 
            
            
            
                //filaSeleccionada[i] = source.getModel().getValueAt(row, i)+"";
                
                //VistaPersona.jTextField_idDocumento.append(source.getModel().getValueAt(row, i));
                VistaPersona.jTextField_idDocumento.setText(String.valueOf(source.getModel().getValueAt(row, 0)));
                VistaPersona.jTextField_nombreUsuario.setText(String.valueOf(source.getModel().getValueAt(row, 1)));
                VistaPersona.jTextField_apellidoUsuario.setText(String.valueOf(source.getModel().getValueAt(row, 2)));
                VistaPersona.jTextField_usuario.setText(String.valueOf(source.getModel().getValueAt(row, 3)));
                VistaPersona.jTextField_contrasena.setText(String.valueOf(source.getModel().getValueAt(row, 4)));
                VistaPersona.jTextField_fecha.setText(String.valueOf(source.getModel().getValueAt(row, 5)));
                
                System.out.println(String.valueOf(source.getModel().getValueAt(row, 0)));
                System.out.println(String.valueOf(source.getModel().getValueAt(row, 1)));
                System.out.println(String.valueOf(source.getModel().getValueAt(row, 2)));
                System.out.println(String.valueOf(source.getModel().getValueAt(row, 3)));
                System.out.println(String.valueOf(source.getModel().getValueAt(row, 4)));
                System.out.println(String.valueOf(source.getModel().getValueAt(row, 5)));
                
                
                setVisible(false);
                dispose(); 
           
            
         
            
        
        
    }//GEN-LAST:event_tblDatosMouseClicked

    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        
       //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Buscar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Buscar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Buscar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Buscar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Buscar().setVisible(true);
            }
            
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    public javax.swing.JTable tblDatos;
    // End of variables declaration//GEN-END:variables
}
